entries/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse

from . import views
from .models import Location,EffortInstance

urlpatterns = [

    url(r'^$', views.GeoJSONView.as_view(), name='location-json'),
    url(r'^index/', views.IndexView.as_view(), name="index"),
    url(r'^test_form/', views.FormView.as_view(), name="test_form"),
    url(r'^(?P<pk>\d+)/results/$', views.service_results, name='service-results'),
    url(r'^shared_servicetype/$', views.shared_servicetype, name='shared-servicetype'),
    url(r'^post_request/$', views.post_request, name='post-request'),
]


'''
There was an issue with the reverse call working for post-request
I tried with the url and with the name; it ended up working with the namespace
django shell:
In [30]: reverse('entries:post-request')
Out[30]: '/entries/post_request/'

>>> from django.core.urlresolvers import reverse
>>> reverse('entries:post-request')
'''

hos/hos/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hos.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

hos2/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.gis import admin

from entries import views as e_views

admin.autodiscover()

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',TemplateView.as_view(template_name='entries/main.html'),name='main'),
    url(r'^find/$', e_views.find_facilities, name='find-facilities'),
    url(r'^all/$', e_views.all_facilities, name='all-facilities'),
    url(r'^entries/', include('entries.urls', namespace='entries')),
]


#

entries/models.py
from django.db import models
from django.db.models import signals
#extra stuff for GeoDjango
from django.contrib.gis.db import models
from django.contrib.gis.geos import *

class ServiceProvider(models.Model):
	service_provider_id =  models.AutoField(primary_key=True)
	provider_name = models.CharField(max_length = 500)
	#provider_name_en = models.CharField(max_length = 500)
	#provider_name_fr = models.CharField(max_length = 500)
	#provider_name_cr = models.CharField(max_length = 500)

class Location(models.Model):
	#latitude and longitude need to be changed to string types for GeoDjango
	latitude = models.CharField(max_length=15, blank=True, null=True)
	longitude = models.CharField(max_length=15, blank=True, null=True) 

	#overriding the default manager with a GeoManager instance. 
	#Changing geography to equal False, and dim(dimension to 2) This will use a geom type and be compatible with the admin polygons
	geom = models.PointField(dim=2, geography=False, blank=True, null=True)
	objects = models.GeoManager()

	def save(self,input_id):
		if self.latitude != None and len(self.latitude) > 0:
			lString = 'POINT(%s %s)' % (self.longitude.strip(), self.latitude.strip())
			self.geom = fromstr(lString)
		super(Location, self).save()

		if self.latitude != None and len(self.latitude) > 0:
			#whenever a location is saved, it creates a new tuple for the Location_w_efforts table, to keep the table up to date
			Location_w_effortsObj = Location_w_efforts()
			Location_w_effortsObj.provider_name = 'test1'
			Location_w_effortsObj.latitude = self.latitude
			Location_w_effortsObj.longitude = self.longitude
			Location_w_effortsObj.id = self.id
			Location_w_effortsObj.date_start = EffortInstance.objects.get(effort_instance_id=input_id).date_start
			Location_w_effortsObj.date_end = EffortInstance.objects.get(effort_instance_id=input_id).date_end
			provider_num = EffortInstance.objects.get(effort_instance_id=input_id).service_provider
			Location_w_effortsObj.service_provider = provider_num
			Location_w_effortsObj.provider_name = ServiceProvider.objects.get(service_provider_id=provider_num.service_provider_id).provider_name
			Location_w_effortsObj.save()
		
class haiti_adm1_minustah(models.Model):
    id_adm1 = models.FloatField()
    adm1 = models.CharField(max_length=45)
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()
    
    def __unicode__(self):
        return self.adm1

class haiti_adm2_minustah(models.Model):
    id_adm1 = models.FloatField()
    adm1 = models.CharField(max_length=45)
    id_adm2 = models.FloatField()
    adm2 = models.CharField(max_length=45)
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    pop = models.IntegerField()
    sq_miles = models.FloatField()
    pop_sq_mi = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()
    
    def __unicode__(self):
        return self.adm2
        
class haiti_adm3_minustah(models.Model):
    id_adm1 = models.FloatField()
    adm1 = models.CharField(max_length=45)
    id_adm2 = models.FloatField()
    adm2 = models.CharField(max_length=45)
    id_adm3 = models.FloatField()
    nom_adm3 = models.CharField(max_length=45)
    adm3 = models.CharField(max_length=45)
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()
    
    def __unicode__(self):
        return self.adm3
        
class haiti_adm4_minustah(models.Model):
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    id_adm1 = models.FloatField()
    adm1 = models.CharField(max_length=45)
    id_adm2 = models.FloatField()
    adm2 = models.CharField(max_length=45)
    id_adm3 = models.FloatField()
    nom_adm3 = models.CharField(max_length=45)
    adm3 = models.CharField(max_length=45)
    no_adm4 = models.FloatField()
    id_adm4 = models.CharField(max_length=45)
    nom_adm4 = models.CharField(max_length=45)
    adm4 = models.CharField(max_length=45)
    shape_le_1 = models.FloatField()
    shape_ar_1 = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()
    
    def __unicode__(self):
        return self.adm4

class Common_EffortInstance_Info(models.Model):
	TRAVELING_TEAM = 'TT'
	CLINIC = 'CL'
	HOSPITAL = 'HL'
	TYPE_OPTIONS = (
		(TRAVELING_TEAM, 'Traveling Team'),
		(CLINIC, 'Clinic'),
		(HOSPITAL, 'Hospital'),
	)
	
	#effort_instance_id =  models.IntegerField(primary_key=True)
	service_provider = models.ForeignKey(ServiceProvider, blank=True, null=True)
	type = models.CharField(max_length=2, choices=TYPE_OPTIONS, default=CLINIC)
	date_start = models.DateTimeField(auto_now=False, null=True)
	date_end = models.DateTimeField(auto_now=False, null=True)
	default = models.NullBooleanField(primary_key=False, blank=True)
	description = models.CharField(max_length=600, blank=True)
	
	drupal_id = models.IntegerField(default=0)
	
	class Meta:
		abstract = True
        
class EffortInstance(Common_EffortInstance_Info):
	effort_instance_id =  models.IntegerField(primary_key=True)
	updated_on = models.DateTimeField(auto_now=False, null=True)
	updated_by = models.CharField(max_length=100, blank=True)
	#location = models.ForeignKey(Location,blank=True, null=True)
	#change Location to One-to-one relationship: https://docs.djangoproject.com/en/1.7/topics/db/examples/one_to_one/
	location = models.OneToOneField(Location,blank=True, null=True)
	adm_1 = models.ForeignKey(haiti_adm1_minustah, blank=True, null=True)
	adm_2 = models.ForeignKey(haiti_adm2_minustah, blank=True, null=True)
	adm_3 = models.ForeignKey(haiti_adm3_minustah, blank=True, null=True)
	
class ServiceType(models.Model):
    service_type_id = models.IntegerField(primary_key=True)
    service_name_en = models.CharField(max_length=100, blank=True)
    service_name_fr = models.CharField(max_length=100, blank=True)
    service_name_cr = models.CharField(max_length=100, blank=True)
    #service_description = models.CharField(max_length=300, blank=True)
    
class EffortInstanceService(models.Model):
    effort_instance_service_id = models.AutoField(primary_key=True)
    effort_instance = models.ForeignKey(EffortInstance, blank=True, null=True)
    effort_service_type = models.ForeignKey('ServiceType', blank=True, null=True)
    #effort_service_description = models.CharField(max_length=300, blank=True)
    
#temporary model to display points along with their associated effort instance and service provider
#inherits from the Common_EffortInstance_Info base class
class Location_w_efforts(Common_EffortInstance_Info):
	
	provider_name = models.CharField(max_length = 500)
	
	#you don't need location_id below because you have location field above
	#location_id = models.IntegerField(primary_key=False)
	#latitude and longitude need to be changed to string types for GeoDjango
	latitude = models.CharField(max_length=15, blank=True, null=True)
	longitude = models.CharField(max_length=15, blank=True, null=True) 

	#overriding the default manager with a GeoManager instance. 
	geom = models.PointField(dim=3, geography=True, blank=True, null=True)
	
	objects = models.GeoManager()
	
	def save(self):
		if self.latitude != None and len(self.latitude) > 0:
			lString = 'POINT(%s %s)' % (self.longitude.strip(), self.latitude.strip())
			self.geom = fromstr(lString)
		super(Location_w_efforts, self).save()
		
#temporary model to display points along with their associated effort instance and service provider
#inherits from the Common_EffortInstance_Info base class
class Location_w_efforts_temp(Common_EffortInstance_Info):
	
	#used when finding duplicates
	similarity = models.CharField(max_length = 100,null=True)
	
	provider_name = models.CharField(max_length = 500)
	
	#you don't need location_id below because you have location field above
	#location_id = models.IntegerField(primary_key=False)
	#latitude and longitude need to be changed to string types for GeoDjango
	latitude = models.CharField(max_length=15, blank=True, null=True)
	longitude = models.CharField(max_length=15, blank=True, null=True) 

	#overriding the default manager with a GeoManager instance. 
	geom = models.PointField(dim=3, geography=True, blank=True, null=True)
	
	objects = models.GeoManager()
	
	def save(self):
		if self.latitude != None and len(self.latitude) > 0:
			lString = 'POINT(%s %s)' % (self.longitude.strip(), self.latitude.strip())
			self.geom = fromstr(lString)
		super(Location_w_efforts_temp, self).save()
		
#table to store the spatial clusters results
class Spatial_cluster_results(Common_EffortInstance_Info):

	#effort_instance = models.ForeignKey(EffortInstance, blank=True, null=True)
	effort_instance_id =  models.IntegerField(primary_key=False)
	
	provider_name = models.CharField(max_length = 500)
	
	nearby_points = models.IntegerField(primary_key=False, blank=True, null=True)
	point_checked = models.NullBooleanField(primary_key=False, blank=True)
	
	latitude = models.CharField(max_length=15, blank=True, null=True)
	longitude = models.CharField(max_length=15, blank=True, null=True) 

	#overriding the default manager with a GeoManager instance. 
	geom = models.PointField(dim=3, geography=True, blank=True, null=True)
	objects = models.GeoManager()
	
	def save(self):
		if self.latitude != None and len(self.latitude) > 0:
			lString = 'POINT(%s %s)' % (self.longitude.strip(), self.latitude.strip())
			self.point = fromstr(lString)
		super(Spatial_cluster_results, self).save()
		
#table to store the admin3 point in polygon processing
class Admin_cluster_results(Common_EffortInstance_Info):

	provider_name = models.CharField(max_length = 500)
	
	nearby_points = models.IntegerField(primary_key=False, blank=True, null=True)
	point_checked = models.NullBooleanField(primary_key=False, blank=True)
	

entries/templates/entries/detail.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<label>Services provided by Effort Instance: </label>
<p>

<!--for some reason you can't have the parenthesis after effortinstance.effortinstanceservices_set.all in django templates-->
<!--It is hard to output the services because the template view only likes one model in it-->
{% for service in effortinstance.effortinstanceservice_set.all %}
    <!--<input type="radio" name="service" id="service{{ forloop.counter }}" value="{{ service.effort_instance_service_id }}" />-->
    <label for="service{{ forloop.counter }}">{{ service.effort_service_type.service_name }}</label><br />

{% endfor %}



entries/templates/entries/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'entries/style.css' %}" />
{% if latest_EffortInstance_list %}
    <ul>
    {% for p in latest_EffortInstance_list %}
        <li><a href="{% url 'entries:detail' p.effort_instance_id %}">{{ p.service_provider.provider_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Effort Instances are available.</p>
{% endif %}

entries/templates/entries/main.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Haiti Health Facilities{% endblock title %}
{% block page_title %}Haiti Health Facilities{% endblock page_title %}

{% block extra_css %}
 <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
 <!--[if lte IE 8]>
     <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.ie.css" />
 <![endif]-->
 <style>
    #map { 
        height: 400px;
        width: 6b00px;
     }
 </style>
{% endblock extra_css %}

{% block content %}
<div id="location"></div>
<div id="facilities">Finding facilities...</div>
<div id="map"></div>
{% endblock content %}

{% block extra_js %}
<!--<script>var url = "{% url 'entries.views.find_facilities' %}";</script>-->
<script>var url_all = "{% url 'entries.views.all_facilities' %}";</script>

<script src="{% static 'entries/js/jquery.js' %}" ></script>
<script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

<script src="{% static 'entries/js/map.js' %}" ></script>
{% endblock extra_js %}

entries/templates/entries/map.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Colorado Geologic Map {% endblock title %}
{% block extra_css %}
<style>
    #map {
        width: 800px;
        height: 600px;
       }
 </style>
{% endblock extra_css %}
{% block page_title %}Colorado Geologic Map{% endblock page_title %}

{% block content %}
<div id="map"></div>
{% endblock content %}

{% block extra_js %}
<script>
    var unitUrl = "{% url 'location-json' %}";
    
</script>
<script src="{% static 'entries/openlayers/lib/OpenLayers.js' %}" />
<script src="{% static 'entries/js/project.js' %}"></script>
{% endblock extra_js %}

entries/templates/entries/results.html
<h1>{{ entry.effort_instance_id }}</h1>

<ul>
{% for service in entry.effortinstanceservices_set.all %}
    <li>{{ service.effortinstanceservices_text }} -- {{ service.votes }} vote{{ service.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>




entries/templates/entries/test_form.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% load staticfiles %}

<html>
  <head>
  
  <style>
      #map_canvas {
        width: 500px;
        height: 400px;
      }
    </style>
    <!-- <script src="https://maps.googleapis.com/maps/api/js"></script> -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script type="text/javascript">
	$(document).ready(function() {
		$('.ajaxProgress').hide();
		$('.success').hide();
		$('.matching_name').hide()
		$('.nearby_location').hide()
	});
	</script>
	
	<script>
	
	//haha I need to declare the map variable here to call it later in the ajaxRequest function!
	var map;
	var myLatlng = new google.maps.LatLng(19.738571, -72.196125);
	var marker2;
	
  function initialize() {
    var mapCanvas = document.getElementById('map_canvas');
    
    var mapOptions = {
      center: myLatlng,
      zoom: 13,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    map = new google.maps.Map(mapCanvas, mapOptions);
    
    
    var marker = new google.maps.Marker({
    position: myLatlng,
    draggable:true,
    icon: "{% static "entries/img/purple_MarkerA.png" %}"
    //title:"Hello World!"
	});

	// To add the marker to the map, call setMap();
	marker.setMap(map);

	 google.maps.event.addListener(marker, "dragend", function(){
        document.getElementById("lat").value=marker.position.lat();
        document.getElementById("lon").value=marker.position.lng();
    });
    
  }
  //map.data.loadGeoJson('https://storage.googleapis.com/maps-devrel/google.json');
  google.maps.event.addDomListener(window, 'load', initialize);
    
</script>

	
	<script type="text/javascript">



    function ajaxRequest() {
    	$('.ajaxProgress').show();
    	
    	//I hard-coded sending Cardiovascular,Dental,Diabetes, and Emergency values 
    	//simulating as if they were checked by the user
    	//In a real ver, there would be code that would put only the checkboxes
    	//that were checked on the form in data:
    	
		//builds an array of what checkboxes were checked
		services_array = [];
    	$('input[type=checkbox]:checked').each(function() {
			// Do something interesting
			console.log($(this).attr("id"));
			services_array[services_array.length] = $(this).attr("id");
		});
    	
        $.ajax({
            type: "POST",
            url: "{% url 'entries:post-request' %}",
            dataType: "JSON",
            async: true,
            data: {
            	name : $('#organization').val(),
            	latitude : $('#lat').val(),
            	longitude : $('#lon').val(),
            	services : services_array,
            	//Cardiovascular : $('#Cardiovascular').val(),
            	//Dental : $('#Dental').val(),
            	//Diabetes : $('#Diabetes').val(),
            	//Emergency : $('#Emergency').val(),
            },
            success: function (json) {
                //alert(json);
                //var result = JSON.stringify(json);
                //alert(result);
                $('.matching_name').hide()
                
                
                nearby_facilities_json = json['nearby_facilities']
                
                matching_facilities = json['matching_facilities'];
                
                console.log('testing...')
                console.log(typeof matching_facilities)
                
                //if there are matching facilities with similiar names
                if (typeof matching_facilities != 'undefined') {
    				// variable is defined
    				console.log("should be defined")
    				$('.matching_name').show();
    				var matching_facility_string = JSON.stringify(matching_facilities);
                	//alert(matching_facility_string);
				
					var items = [];
				
					var key, count = 0;
					for(key in json.matching_facilities.features) {
					  if(json.matching_facilities.features.hasOwnProperty(key)) {
						count++;
					  }
					}
					
					console.log('count is: ');
					console.log(count);

					for(var i = 0; i < count; i++){
						console.log(json.matching_facilities.features[i].properties);
						items.push('<p>');
						$.each(json.matching_facilities.features[i].properties, function (key, val) {
								items.push('<li id="' + key + '">' + key + ': ' + val + '</li>');
						});
						
						//calls create_point function, which creates the point
						create_point(matching_facilities.features[i].properties.latitude, matching_facilities.features[i].properties.longitude, matching_facilities.features[i]);
					};
					//this call is good, looked at: http://stackoverflow.com/questions/13462580/iterating-geojson-object-with-javascript
					//console.log(json.matching_facilities.features[0])
				
					$( "<ul/>", {
						"class": "my-new-list",
						html: items.join( "" )
					  }).appendTo( "body" );
				
					$('.ajaxProgress').hide();
					$('.matching_name').show();
				
					$("#output").html(json.type);
					console.log('success' + json);
				
				}
				
				//adds the nearby facilities to the map
				map.data.addGeoJson(nearby_facilities_json);
				
				//if there are nearby facilities
				if (typeof nearby_facilities_json != 'undefined') {
					$('.ajaxProgress').hide();
					$('.nearby_location').show();
				}
                
                //not working for some reason
                //map.data.overrideStyle(map.data.getFeatureById('match'), {icon: "{% static "entries/img/purple_MarkerA.png" %}"});
                
                //just create a new marker with same lat lon
                //console.log(matching_facilities.features[0].properties.latitude)
                //console.log(matching_facilities.features[0].properties.longitude)
                
                function create_point(lat,lon,featureInfo) {
                	var matching_facility_marker = new google.maps.LatLng(lat,lon);
                	// To add the marker to the map, use the 'map' property
                	var matching_marker = new google.maps.Marker({
						position: matching_facility_marker,
						title:"Hello World!",
						icon: "{% static "entries/img/purple_MarkerA.png" %}"
					});
					var contentString = 'pop up box'
					//https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple
					var infowindow = new google.maps.InfoWindow({
      					//content: JSON.stringify(featureInfo)
      					content: JSON.stringify(featureInfo.properties.provider_name)
  					});
  					google.maps.event.addListener(matching_marker, 'click', function() {
    					infowindow.open(map,matching_marker);
  					});

					// To add the marker to the map, call setMap();
					matching_marker.setMap(map);
                }
                
            }
        });
        
    }
    
	</script>


</head>

	
  <body>
 
{% comment %}
<form action= "{% url 'entries:post-request' %}" method="post" name="test_form">
{% csrf_token %}
{% endcomment %}

<form onsubmit="return false;">
<br>
Organization: <input type="text" id = "organization" name="organization" style="width: 300px;"><br>
<br>
Select provided services:
<br>
<br>
<input type="checkbox" id="Cardiovascular" name="Cardiovascular" value="Cardiovascular">Cardiovascular<br>
<input type="checkbox" id="Dental" name="Dental" value="Dental">Dental<br>
<input type="checkbox" id="Diabetes" name="Diabetes" value="Diabetes">Diabetes<br>
<input type="checkbox" id="Emergency" name="Emergency" value="Emergency">Emergency<br>
<br>
lat: <input id="lat" type="text" name="lat" style="width: 150px;"> lon: <input id="lon" type="text" name="lon" style="width: 150px;"> 
<br>
<br>
<div id="map_canvas"></div>
<br>
<button class="updateButton" onclick="ajaxRequest()">Submit</Button>
{% comment %}
<input type="submit" value="Create new account" />
{% endcomment %}
</form>

<div id="output">
	<div class = "ajaxProgress">
		<h3>please wait...</h3>
	</div>
	<div class = "success">
		<h3>Success!</h3>
	</div>
	<div class = "matching_name">
		<h3>At least one entry exists in the database with a similar name. Please verify new entry.</h3>
	</div>
	<div class = "nearby_location">
		<h3>At least existing health facility is within 100 meters from your location. Please verify new entry.</h3>
	</div>
	
</div>

<br>

 </body>
 

</html>

